### ISSUE TITLE
package failes after upgrade to 0.52

### ISSUE THREAD

**Issue by emsquared-inc** [atom/vim-mode#768]
[Enter steps to reproduce below:]

1. ...open an HTML file
2. ...hit the escape key

**Atom Version**: 0.196.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.55.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/emintz/.atom/packages/vim-mode/lib/vim-state.coffee:591

TypeError: undefined is not a function
  at getChangesSinceCheckpoint (/home/emintz/.atom/packages/vim-mode/lib/vim-state.coffee:591:6)
  at VimState.module.exports.VimState.deactivateInsertMode (/home/emintz/.atom/packages/vim-mode/lib/vim-state.coffee:411:15)
  at VimState.module.exports.VimState.activateCommandMode (/home/emintz/.atom/packages/vim-mode/lib/vim-state.coffee:377:6)
  at atom-text-editor.registerCommands.activate-command-mode (/home/emintz/.atom/packages/vim-mode/lib/vim-state.coffee:64:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -1:10.8.0 emmet:balance-outward (atom-text-editor.editor)
     -1:09.1.0 core:move-down (atom-text-editor.editor)
     -1:08.4.0 core:move-up (atom-text-editor.editor)
 30x -1:08.0 core:move-down (atom-text-editor.editor)
     -1:05.5.0 core:move-up (atom-text-editor.editor)
 53x -1:05.0 core:move-down (atom-text-editor.editor)
  3x -1:00.4.0 emmet:balance-outward (atom-text-editor.editor)
     -0:57.5.0 editor:consolidate-selections (atom-text-editor.editor)
     -0:57.5.0 core:cancel (atom-text-editor.editor)
     -0:57.3.0 editor:consolidate-selections (atom-text-editor.editor)
     -0:57.3.0 core:cancel (atom-text-editor.editor)
  3x -0:54.4.0 core:move-down (atom-text-editor.editor)
 65x -0:53.5.0 core:move-up (atom-text-editor.editor)
     -0:48.3.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -0:44.5.0 core:backspace (atom-text-editor.editor.mini)
     -0:01.5.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "vim-mode": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
AtLilyPond, v1.2.0
angularjs, v0.3.0
atom-typescript, v4.5.0
atom-yeoman, v0.3.11
autocomplete-plus, v2.18.1
color-picker, v1.7.0
data-atom, v0.6.1
emmet, v2.3.12
linter, v1.2.3
minimap, v4.10.0
omnisharp-atom, v0.4.29
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hey @emsquared-inc, you're on an extremely outdated version of Atom.  Could you try updating to the latest version (currently 1.0.2) and see if you can still reproduce this?  Thanks.
